### PR TITLE
Feat: Converted to NET Standard 1.1 and NUnit 3

### PR DESCRIPTION
**Pull request by thomaswurtz**
Converted to new cs proj format, NET Standard 1.1 and NUnit 3.

Also changed so that the nuspec is in the csproj file. Changed the PackageId to DNParser.Standard in there and set the version to 1.3.0. Not sure if you like to keep the existing package id so this is something you may want to review and update 🙂 

Let me know if you have any questions or want me to change something in the PR

### CODE REVIEW

**Comment by picrap** [comment]
Shame, it doesn't build. As I said in the related issue, it would be great to keep both versions: .NET Standard and .NET 4.0.

**Comment by thomaswurtz** [comment]
I see, no problem. I updated the PR to have multi target support so .NET 4.0 should also be supported.

I'm not familiar with appveyor and how it is setup, but looks like the appveyor.yml file needs to be updated to use newer msbuild version. Is this something you can update, or provide instructions on?

**Comment by picrap** [comment]
I think that for file `appveyor.yml` line stating `os: Visual Studio 2015` should be changed to `os: Visual Studio 2017` (hoping it works) and the section starting with `install:` should be removed. This is a wild guess and I'm at work, so sorry for not having much time 😉

**Comment by thomaswurtz** [comment]
Did another attempt based on your feedback, looks better now I think 😃

**Comment by picrap** [comment]
Brilliant! Thanks ❤️

**Comment by thomaswurtz** [comment]
Thanks!
You may want to look at the metadata in the nuget before publishing to nuget.org.
Not sure what to write in that copyright field for example. Should probably have left it the way it was before 😄

**Comment by picrap** [comment]
It looked fine, so I kept it this way.

**Pull request merged**
